# python-api-chart/values-prod.yaml

# Override the full name of the release to be specific to prod
fullnameOverride: "python-api-prod"

# Production environment typically has more replicas for high availability
replicaCount: 3

# Image settings - always use a stable, versioned tag
image:
  repository: miuasyehor/python-api
  pullPolicy: IfNotPresent # Or Always if you have a robust CI/CD for rollbacks
  tag: "latest" # Your Docker image tag

# HPA settings for prod
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10 # Allow significant scaling for production load
  targetMemoryUtilizationPercentage: 80 # Standard target

# Resource requests and limits for prod (should be well-tuned for performance and stability)
resources:
  requests:
    memory: "500Mi"
    cpu: "1"
  limits:
    memory: "1Gi" # Allow more headroom for memory in prod
    cpu: "2"

# Busybox load generator settings for prod
busyboxLoadgen:
  enabled: false # Definitely disabled in prod

# Production-specific settings
service:
  type: ClusterIP # Typically ClusterIP, exposed via Ingress or LoadBalancer externally
  port: 80
  targetPort: 5000

# Example: Enable ingress with production hostname and TLS
ingress:
  enabled: false # Set to true if you use ingress for prod
  # className: "nginx"
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod" # Example for cert-manager
  # hosts:
  #   - host: python-api.example.com
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls:
  #   - secretName: prod-python-api-tls # Secret managed by cert-manager or manually
  #     hosts:
  #       - python-api.example.com

# Consider adding podAntiAffinity for production to spread pods across nodes
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - python-api-chart
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - my-python-api-prod
          topologyKey: "kubernetes.io/hostname"