# python-api-chart/values-dev.yaml

# Override the full name of the release to be specific to dev
fullnameOverride: "python-api-dev"

# Development environment typically has fewer replicas
replicaCount: 1

# Image settings - you might use a specific dev tag or branch
image:
  repository: miuasyehor/python-api
  pullPolicy: IfNotPresent # Or Always if you frequently update dev images
  tag: "latest" # Your Docker image tag

# HPA settings for dev
hpa:
  enabled: true # Or false if you don't need HPA in dev
  minReplicas: 1
  maxReplicas: 2 # Allow some scaling but keep it small
  targetMemoryUtilizationPercentage: 75 # Potentially a more relaxed target for dev

# Resource requests and limits for dev (might be lower than prod)
resources:
  requests:
    memory: "256Mi"
    cpu: "0.5"
  limits:
    memory: "512Mi"
    cpu: "1"

# Busybox load generator settings for dev
busyboxLoadgen:
  enabled: false # Typically disabled in dev unless specifically testing this feature
  # resources: # Can be lower if enabled
  #   requests:
  #     memory: "100Mi"
  #     cpu: "50m"
  #   limits:
  #     memory: "150Mi"
  #     cpu: "100m"

# Other dev-specific settings can be added here
# For example, disabling ingress or using a different service type
service:
  type: ClusterIP # Or NodePort for easy access in some dev setups
  port: 80
  targetPort: 5000

# Example: Disable ingress for dev
ingress:
  enabled: false