apiVersion: v1
kind: Pod
metadata:
  name: python-api-pod
spec:
  containers:
    - name: python-api
      image: miuasyehor/python-api:latest
      ports:
        - containerPort: 5000
  imagePullSecrets:
    - name: regcred
