name: CI Pipeline for Python API

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
  workflow_dispatch:

jobs:
  sast-scan:
    name: Run SAST Scan (Bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: bandit -r Python-api -ll

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sast-scan
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Python-api
          push: true
          tags: miuasyehor/python-api:latest