# python-api-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-api-chart.fullname" . }}
  labels:
    {{- include "python-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} # Can use the port name 'http' from Deployment
      protocol: TCP
      name: http
  selector:
    {{- include "python-api-chart.selectorLabels" . | nindent 4 }}